# Generated by Django 5.2.13 on 2026-04-13 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin / Agency Manager'), ('project_manager', 'Project Manager'), ('team_head', 'Team Head'), ('specialist', 'Specialist / Creator'), ('sales_manager', 'Sales Manager'), ('client', 'Client')], db_index=True, default='specialist', max_length=32),
        ),
    ]
