# Generated by Django 5.2.13 on 2026-04-13 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('project_manager', 'Project Manager'), ('team_head', 'Team Head'), ('team_member', 'Team Member'), ('sales_manager', 'Sales Manager'), ('client', 'Client')], db_index=True, default='team_member', max_length=32),
        ),
    ]
