# Generated by Django 5.2.13 on 2026-05-02 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin / Agency Manager'), ('project_manager', 'Project Manager'), ('team_head', 'Team Head'), ('specialist', 'Specialist / Creator'), ('hr', 'Human Resources'), ('sales_manager', 'Sales Manager'), ('client', 'Client')], db_index=True, default='specialist', max_length=32),
        ),
    ]
