# Generated by Django 5.2.15 on 2026-06-08 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_user_last_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin / Agency Manager'), ('project_manager', 'Project Manager'), ('team_head', 'Team Head'), ('specialist', 'Specialist / Creator'), ('hr', 'Human Resources'), ('sales_manager', 'Strategist'), ('client', 'Client')], db_index=True, default='specialist', max_length=32),
        ),
    ]
