# Generated by Django 5.2.15 on 2026-07-27 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailotp',
            name='failed_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='emailotp',
            name='locked_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
