# Generated by Django 5.2.13 on 2026-04-17 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tms', '0003_jobtitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='label',
            name='color_hint',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='workitem',
            name='board_position',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
