# Generated by Django 5.2.13 on 2026-04-20 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tms', '0004_alter_label_color_hint_alter_workitem_board_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='workitem',
            name='scheduled_date',
            field=models.DateField(blank=True, help_text='Date when work is planned to start', null=True),
        ),
    ]
