# Generated by Django 5.2.13 on 2026-04-27 05:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tms', '0007_workitem_timer_start'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['created_at'], name='tms_activit_created_5c2676_idx'),
        ),
        migrations.AddIndex(
            model_name='backup',
            index=models.Index(fields=['created_at'], name='tms_backup_created_554420_idx'),
        ),
        migrations.AddIndex(
            model_name='timelog',
            index=models.Index(fields=['logged_at'], name='tms_timelog_logged__b49eb7_idx'),
        ),
        migrations.AddIndex(
            model_name='timelog',
            index=models.Index(fields=['user'], name='tms_timelog_user_id_c65531_idx'),
        ),
        migrations.AddIndex(
            model_name='timelog',
            index=models.Index(fields=['work_item'], name='tms_timelog_work_it_e17103_idx'),
        ),
        migrations.AddIndex(
            model_name='workitem',
            index=models.Index(fields=['created_at'], name='tms_workite_created_95bc90_idx'),
        ),
        migrations.AddIndex(
            model_name='workitem',
            index=models.Index(fields=['updated_at'], name='tms_workite_updated_a3cff2_idx'),
        ),
    ]
