# Generated by Django 5.2.13 on 2026-04-27 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tms', '0008_activitylog_tms_activit_created_5c2676_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='color',
            field=models.CharField(default='#6366f1', max_length=7),
        ),
    ]
