# Generated by Django 5.2.13 on 2026-04-28 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tms', '0012_workitem_reference_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workitem',
            name='reference_link',
            field=models.TextField(blank=True, help_text='Store multiple links separated by spaces or newlines', null=True),
        ),
    ]
