# Generated by Django 5.2.13 on 2026-04-25 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tms', '0006_backup'),
    ]

    operations = [
        migrations.AddField(
            model_name='workitem',
            name='timer_start',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the last In Progress session started', null=True),
        ),
    ]
