# Generated by Django 5.2.13 on 2026-04-27 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tms', '0009_project_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='color',
            field=models.CharField(default='#94a3b8', max_length=7),
        ),
    ]
