# Generated by Django 5.2.13 on 2026-04-27 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tms', '0010_state_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='workitem',
            name='is_client_approved',
            field=models.BooleanField(default=False),
        ),
    ]
