# Generated by Django 5.2.13 on 2026-04-27 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tms', '0011_workitem_is_client_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='workitem',
            name='reference_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
