# Generated by Django 5.2.13 on 2026-04-30 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tms', '0013_alter_workitem_reference_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='workitem',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workitem',
            name='posting_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
