# Generated by Django 5.2.13 on 2026-04-30 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tms', '0014_workitem_deadline_workitem_posting_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='workitem',
            name='last_state_change',
            field=models.DateTimeField(blank=True, help_text='Timestamp of the most recent state transition', null=True),
        ),
        migrations.AddField(
            model_name='workitem',
            name='rework_count',
            field=models.PositiveIntegerField(default=0, help_text='Total number of times this task was sent back for revision'),
        ),
        migrations.AddField(
            model_name='workitem',
            name='state_durations',
            field=models.JSONField(default=dict, help_text="Total minutes spent in each state: {'state_name': minutes}"),
        ),
    ]
