# Generated by Django 5.2.13 on 2026-05-04 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tms', '0015_workitem_last_state_change_workitem_rework_count_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workitem',
            options={'ordering': ['-scheduled_date', '-updated_at']},
        ),
    ]
