# Generated by Django 5.2.13 on 2026-05-04 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tms', '0016_alter_workitem_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workitem',
            options={'ordering': ['due_date', '-updated_at']},
        ),
    ]
