# Generated by Django 5.2.13 on 2026-06-04 11:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tms', '0017_alter_workitem_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='job_title',
            field=models.ForeignKey(blank=True, help_text='Designation/Specialist type that is allowed to work on this module', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modules', to='tms.jobtitle'),
        ),
        migrations.AddField(
            model_name='workitem',
            name='content_writer',
            field=models.ForeignKey(blank=True, help_text='Content writer assigned to create content for this task', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_writer_work_items', to=settings.AUTH_USER_MODEL),
        ),
    ]
