# Generated by Django 5.2.15 on 2026-06-08 04:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tms', '0018_module_job_title_workitem_content_writer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectStrategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('is_deployed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_strategies', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strategies', to='tms.project')),
            ],
            options={
                'verbose_name_plural': 'Project strategies',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='workitem',
            name='strategy',
            field=models.ForeignKey(blank=True, help_text='The strategy group this task belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_items', to='tms.projectstrategy'),
        ),
    ]
